runtime: nodejs20
instance_class: F2
entrypoint: npm run start:prod

env_variables:
  NODE_ENV: production
  PORT: 8080
  MONGODB_URI: mongodb+srv://test:test@cluster0.vib3n.mongodb.net/
  EMAIL_PASSWORD: rjxx cuka qxjw gcbx

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
